### ISSUE TITLE
NoMethodError: undefined method `logical_paths' for nil:NilClass

### ISSUE THREAD

**Issue by leonsp** [kavkaz/js_assets#11]
I get this error during precompilation:

    NoMethodError: undefined method `logical_paths' for nil:NilClass
    /usr/local/rvm/gems/ruby-2.2.2/gems/js_assets-0.1.0/lib/js_assets/list.rb:10:in `fetch'
    /usr/local/rvm/gems/ruby-2.2.2/gems/js_assets-0.1.0/app/assets/javascripts/app_assets.js.erb:1:in `_evaluate_template'

This is the relevant line:

    ::Rails.application.assets.logical_paths do |logical_path, filename|

It's legal for `Rails.application.assets` to be `nil` in production:

> https://github.com/rails/sprockets-rails
>
> `config.assets.compile`
>
> Enables Sprockets compile environment. If disabled, Rails.application.assets will be `nil` to prevent inadvertent compilation calls. View helpers will depend on assets being precompiled to public/assets in order to link to them. Initializers expecting Rails.application.assets during boot should be accessing the environment in a config.assets.configure block. See below.

**Comment by joemsak** [comment]
I'm having this same trouble with the updated patch in Rails 5 / Sprockets 4 - please excuse my ignorance: is there something else I should do besides use this gem as Im trying to upgrade a legacy rails app? I am not familiar with why the devs (who are no longer around) may have chosen to use this gem and if there is an equivalent behavior in newer versions of rails due to webpacker, et al. Thanks!
